"""initial_state_from_existing_db

Revision ID: 7f67dfef9906
Revises: 
Create Date: 2026-05-14 10:14:49.745339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f67dfef9906'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doc_fts_content')
    op.drop_table('doc_fts_config')
    op.drop_table('doc_fts_data')
    op.drop_table('doc_fts_docsize')
    op.drop_table('doc_fts_idx')
    op.drop_table('doc_fts')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.alter_column('resource_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('ip_address',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=64),
               existing_nullable=True)

    with op.batch_alter_table('contribution_configs', schema=None) as batch_op:
        batch_op.alter_column('initial_treasury',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('tier_selection_open',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('doc_folders', schema=None) as batch_op:
        batch_op.alter_column('write_min_grade',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('ALL', 'APPRENTI', 'COMPAGNON', 'MAITRE', name='mingrade'),
               existing_nullable=False,
               existing_server_default=sa.text("'ALL'"))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_doc_folders_download_group_id_lodge_groups'), 'lodge_groups', ['download_group_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_doc_folders_personal_owner_id_members'), 'members', ['personal_owner_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_doc_folders_group_id_lodge_groups'), 'lodge_groups', ['group_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_doc_folders_write_group_id_lodge_groups'), 'lodge_groups', ['write_group_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('doc_spaces', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_doc_spaces_group_id_lodge_groups'), 'lodge_groups', ['group_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('DRAFT', 'SUBMITTED', 'VALIDATED', 'PUBLISHED', name='docstatus'),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_documents_folder_id_doc_folders'), 'doc_folders', ['folder_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('lodge_events', schema=None) as batch_op:
        batch_op.alter_column('visibility',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('ALL', 'MAITRES', 'COMPAGNONS_ET_MAITRES', 'APPRENTIS', 'OFFICERS', 'GROUP', 'ADMIN', name='eventvisibility'),
               existing_nullable=False)
        batch_op.alter_column('is_personal',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_lodge_events_visibility_group_id_lodge_groups'), 'lodge_groups', ['visibility_group_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('lodge_settings', schema=None) as batch_op:
        batch_op.alter_column('attendance_threshold_warn',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('(70)'))
        batch_op.alter_column('attendance_threshold_danger',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('(50)'))

    with op.batch_alter_table('mailing_deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mailing_deliveries_external_id'), ['external_id'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_mailing_deliveries_external_id_external_contacts'), 'external_contacts', ['external_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.alter_column('membership_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('APPARTENANCE', 'AFFILIATION', name='membershiptype'),
               existing_nullable=False,
               existing_server_default=sa.text("'APPARTENANCE'"))

    with op.batch_alter_table('planches', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_planches_archived_doc_id_documents'), 'documents', ['archived_doc_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_parent_task_id'), ['parent_task_id'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_tasks_assigned_to_id_members'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_tasks_parent_task_id_tasks'), 'tasks', ['parent_task_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_tasks_forum_subject_id_forum_subjects'), 'forum_subjects', ['forum_subject_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_tasks_assigned_to_id_members'), 'members', ['assigned_to_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_tasks_assigned_to_group_id_lodge_groups'), 'lodge_groups', ['assigned_to_group_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tasks_assigned_to_group_id_lodge_groups'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_tasks_assigned_to_id_members'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_tasks_forum_subject_id_forum_subjects'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_tasks_parent_task_id_tasks'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_tasks_assigned_to_id_members'), 'members', ['assigned_to_id'], ['id'])
        batch_op.create_foreign_key(None, 'forum_subjects', ['forum_subject_id'], ['id'])
        batch_op.create_foreign_key(None, 'tasks', ['parent_task_id'], ['id'])
        batch_op.create_foreign_key(None, 'lodge_groups', ['assigned_to_group_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_tasks_parent_task_id'))

    with op.batch_alter_table('planches', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_planches_archived_doc_id_documents'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'documents', ['archived_doc_id'], ['id'])

    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.alter_column('membership_type',
               existing_type=sa.Enum('APPARTENANCE', 'AFFILIATION', name='membershiptype'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'APPARTENANCE'"))

    with op.batch_alter_table('mailing_deliveries', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_mailing_deliveries_external_id_external_contacts'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'external_contacts', ['external_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_mailing_deliveries_external_id'))

    with op.batch_alter_table('lodge_settings', schema=None) as batch_op:
        batch_op.alter_column('attendance_threshold_danger',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('(50)'))
        batch_op.alter_column('attendance_threshold_warn',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('(70)'))

    with op.batch_alter_table('lodge_events', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_lodge_events_visibility_group_id_lodge_groups'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'lodge_groups', ['visibility_group_id'], ['id'])
        batch_op.alter_column('is_personal',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('visibility',
               existing_type=sa.Enum('ALL', 'MAITRES', 'COMPAGNONS_ET_MAITRES', 'APPRENTIS', 'OFFICERS', 'GROUP', 'ADMIN', name='eventvisibility'),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_documents_folder_id_doc_folders'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'doc_folders', ['folder_id'], ['id'])
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.Enum('DRAFT', 'SUBMITTED', 'VALIDATED', 'PUBLISHED', name='docstatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('doc_spaces', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_doc_spaces_group_id_lodge_groups'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'lodge_groups', ['group_id'], ['id'])

    with op.batch_alter_table('doc_folders', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_doc_folders_write_group_id_lodge_groups'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_doc_folders_group_id_lodge_groups'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_doc_folders_personal_owner_id_members'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_doc_folders_download_group_id_lodge_groups'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'lodge_groups', ['group_id'], ['id'])
        batch_op.create_foreign_key(None, 'lodge_groups', ['download_group_id'], ['id'])
        batch_op.create_foreign_key(None, 'members', ['personal_owner_id'], ['id'])
        batch_op.create_foreign_key(None, 'lodge_groups', ['write_group_id'], ['id'])
        batch_op.alter_column('write_min_grade',
               existing_type=sa.Enum('ALL', 'APPRENTI', 'COMPAGNON', 'MAITRE', name='mingrade'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'ALL'"))

    with op.batch_alter_table('contribution_configs', schema=None) as batch_op:
        batch_op.alter_column('tier_selection_open',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('initial_treasury',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.alter_column('ip_address',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('resource_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    op.create_table('doc_fts',
    sa.Column('doc_id', sa.NullType(), nullable=True),
    sa.Column('title', sa.NullType(), nullable=True),
    sa.Column('body', sa.NullType(), nullable=True)
    )
    op.create_table('doc_fts_idx',
    sa.Column('segid', sa.NullType(), nullable=False),
    sa.Column('term', sa.NullType(), nullable=False),
    sa.Column('pgno', sa.NullType(), nullable=True),
    sa.PrimaryKeyConstraint('segid', 'term')
    )
    op.create_table('doc_fts_docsize',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('sz', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doc_fts_data',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('block', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doc_fts_config',
    sa.Column('k', sa.NullType(), nullable=False),
    sa.Column('v', sa.NullType(), nullable=True),
    sa.PrimaryKeyConstraint('k')
    )
    op.create_table('doc_fts_content',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('c0', sa.NullType(), nullable=True),
    sa.Column('c1', sa.NullType(), nullable=True),
    sa.Column('c2', sa.NullType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
